/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package openchat;

import io.javalin.Javalin;
import openchat.api.LoginAPI;
import openchat.api.UsersAPI;
import openchat.domain.users.IdGenerator;
import openchat.domain.users.UserRepository;
import openchat.domain.users.UserService;

public class App {
    private UsersAPI usersAPI;
	private LoginAPI loginAPI;
    
    public App() {
    	IdGenerator idGenerator = new IdGenerator();
    	UserRepository userRepository = new UserRepository();
		UserService userService = new UserService(idGenerator, userRepository);
		usersAPI = new UsersAPI(userService);
		loginAPI = new LoginAPI(userRepository);
	}

	public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
    	App mainApp = new App();
        Javalin app = Javalin.create().start(getHerokuAssignedPort());
        app.get("/status", ctx -> ctx.result("Open chat"));
        app.post("/users", ctx -> mainApp.usersAPI.createUser(ctx));
        app.post("/login", ctx -> mainApp.loginAPI.login(ctx));
        app.get("/*", ctx -> ctx.result("API not implemented"));
    }
    
    private static int getHerokuAssignedPort() {
        String herokuPort = System.getenv("PORT");
        if (herokuPort != null) {
          return Integer.parseInt(herokuPort);
        }
        return 7000;
      }
}
